services:
  db:
    image: postgres:17
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  web:
    build: .
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./:/app
      - ./init-db/backup.dump:/app/backup.dump
    networks:
      - backend
    command: >
      sh -c "
        sh /scripts/wait-for-postgres.sh &&
        poetry run python manage.py migrate --noinput &&
        sh /scripts/restore-db.sh &&
        poetry run python manage.py runserver 0.0.0.0:8000
      "

volumes:
  postgres_data:

networks:
  backend:
    driver: bridge